# Generated by Django 5.2.4 on 2025-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_faculty_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
