# Generated by Django 5.2.4 on 2025-07-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_attendance_course_remove_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('assignment', 'Assignment'), ('final', 'Final Exam')], max_length=50)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
        ),
    ]
