# Generated by Django 5.2.4 on 2025-07-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_assessmenttype_subject_remove_marks_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='score',
            new_name='marks',
        ),
    ]
