# Generated by Django 5.2.4 on 2025-07-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_rename_score_marks_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='assessment_type',
            field=models.CharField(choices=[('unit', 'Unit Test'), ('quiz', 'Quiz'), ('midterm', 'Midterm'), ('assignment', 'Assignment'), ('final', 'Final Exam')], max_length=50),
        ),
    ]
