# Generated by Django 5.2.4 on 2025-07-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_quiz_subject_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('experience', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='faculty_photos/')),
            ],
        ),
    ]
