# Generated by Django 5.2.4 on 2025-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_quiz_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
