# Generated by Django 5.2.4 on 2025-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
